exclude: ^(qwt)/

ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args:
        -   --skip=*.ts,*.svg,*.hqx,*-inv.txt,*.iss.in,*.dox.in
        -   --ignore-words=.codespell_ignore_words.txt

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args:
        -   --py36-plus

-   repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
    -   id: sphinx-lint
